jobs:
- job: BuildPkg

  pool: mac-mini

  steps:
  - script: |
      ./ci/build_android_plugin.sh
      ./ci/build_windows_plugin.sh
      ./ci/build_mac_plugin.sh
      sh ./ci/build_webgl138_plugin.sh

  - script: |
      cd tests
      ./build_unity_pkg.sh
  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: './Effekseer.unitypackage'
        ArtifactName: 'package'
        publishLocation: 'Container'
  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: './Dev/Plugin/Assets/'
        ArtifactName: 'Assets'
        publishLocation: 'Container'
  - script: |
      cd tests
      ./build_unity_android.sh
      dg deploy TestProject/Build/Android.apk
