on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone --depth 1 https://github.com/effekseer/Effekseer.git ../Effekseer
      - name: build script
        run: |
          cd Dev/Cpp/android
          $ANDROID_SDK_ROOT/ndk-bundle/ndk-build clean NDK_PROJECT_PATH=./ NDK_APPLICATION_MK=jni/Application_x86.mk
          $ANDROID_SDK_ROOT/ndk-bundle/ndk-build -j4  NDK_PROJECT_PATH=./ NDK_APPLICATION_MK=jni/Application_x86.mk
          cp libs/x86/libEffekseerUnity.so ../../Plugin/Assets/Effekseer/Plugins/Android/libs/x86/
          $ANDROID_SDK_ROOT/ndk-bundle/ndk-build clean NDK_PROJECT_PATH=./ NDK_APPLICATION_MK=jni/Application_armeabi-v7a.mk
          $ANDROID_SDK_ROOT/ndk-bundle/ndk-build -j4  NDK_PROJECT_PATH=./ NDK_APPLICATION_MK=jni/Application_armeabi-v7a.mk
          cp libs/armeabi-v7a/libEffekseerUnity.so ../../Plugin/Assets/Effekseer/Plugins/Android/libs/armeabi-v7a/
          $ANDROID_SDK_ROOT/ndk-bundle/ndk-build clean  NDK_PROJECT_PATH=./ NDK_APPLICATION_MK=jni/Application_arm64-v8a.mk
          $ANDROID_SDK_ROOT/ndk-bundle/ndk-build -j4  NDK_PROJECT_PATH=./ NDK_APPLICATION_MK=jni/Application_arm64-v8a.mk
          cp libs/arm64-v8a/libEffekseerUnity.so ../../Plugin/Assets/Effekseer/Plugins/Android/libs/arm64-v8a/
      - name: Upload math result for android
        uses: actions/upload-artifact@v1
        with:
          name: Android
          path: ./Dev/Plugin/Assets/Effekseer/Plugins

  mac_ios:
    name: mac iOS Build
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v2
      - run: git clone --depth 1 https://github.com/effekseer/Effekseer.git ../Effekseer
      - run: cd  ./Dev/Cpp/macosx/ && ./Build.sh
      - name: Upload ios
        uses: actions/upload-artifact@v1
        with:
          name: mac_iOS
          path: ./Dev/Plugin/Assets/Effekseer/Plugins

  windows:
    name: windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone --recursive --depth 1 https://github.com/effekseer/Effekseer.git ../Effekseer
      - name: Build
        run: cd ./Dev/Cpp/windows && Build.bat
        shell: cmd
      - name: Upload math result
        uses: actions/upload-artifact@v1
        with:
          name: Windows
          path: ./Dev/Plugin/Assets/Effekseer/Plugins

  webgl:
    name: wrbgl Build with emsdk
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2


      - run: git clone --depth 1 https://github.com/effekseer/Effekseer.git ../Effekseer


      - run: |
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install sdk-fastcomp-tag-1.38.11-64bit
          ./emsdk activate sdk-fastcomp-tag-1.38.11-64bit
          source ./emsdk_env.sh
          cd ..

          cd ./Dev/Cpp/webgl
          mkdir build138
          cd build138
          emcmake cmake ..
          make
          cp libEffekseerUnity.bc ../../../Plugin/Assets/Effekseer/Plugins/WebGL/1.38.11-64bit/

      - run: |
          cd emsdk
          ./emsdk install sdk-fastcomp-1.37.40-64bit
          ./emsdk activate sdk-fastcomp-1.37.40-64bit
          source ./emsdk_env.sh
          cd ..

          cd ./Dev/Cpp/webgl
          mkdir build137
          cd build137
          emcmake cmake ..
          make
          cp libEffekseerUnity.bc ../../../Plugin/Assets/Effekseer/Plugins/WebGL/

      - name: Upload math result for webgl
        uses: actions/upload-artifact@v1
        with:
          name: WebGL
          path: ./Dev/Plugin/Assets/Effekseer/Plugins

  merge:
    name: merge
    runs-on: windows-latest
    needs: [android, mac_ios, windows, webgl]
    steps:
      - uses: actions/checkout@v2
      - name: Download Android
        uses: actions/download-artifact@v1
        with:
          name: Android

      - name: Download mac_ios
        uses: actions/download-artifact@v1
        with:
          name: mac_iOS

      - name: Download mac_ios
        uses: actions/download-artifact@v1
        with:
          name: Windows

      - name: Download mac_ios
        uses: actions/download-artifact@v1
        with:
          name: WebGL

      - name: Copy
        run: |
          move Android\Android\libs\arm64-v8a\libEffekseerUnity.so Dev\Plugin\Assets\Effekseer\Plugins\Android\libs\arm64-v8a\
          move Android\Android\libs\armeabi-v7a\libEffekseerUnity.so Dev\Plugin\Assets\Effekseer\Plugins\Android\libs\armeabi-v7a\
          move Android\Android\libs\x86\libEffekseerUnity.so Dev\Plugin\Assets\Effekseer\Plugins\Android\libs\x86\
          move mac_iOS\iOS\libEffekseerUnity.a Dev\Plugin\Assets\Effekseer\Plugins\iOS\
          move mac_iOS\EffekseerUnity.bundle\Contents\MacOS\EffekseerUnity Dev\Plugin\Assets\Effekseer\Plugins\EffekseerUnity.bundle\Contents\MacOS\

          move WebGL\WebGL\libEffekseerUnity.bc Dev\Plugin\Assets\Effekseer\Plugins\WebGL\
          move WebGL\WebGL\1.38.11-64bit\libEffekseerUnity.bc Dev\Plugin\Assets\Effekseer\Plugins\WebGL\1.38.11-64bit\
          move Windows\x86\EffekseerUnity.dll Dev\Plugin\Assets\Effekseer\Plugins\x86\
          move Windows\x86_64\EffekseerUnity.dll Dev\Plugin\Assets\Effekseer\Plugins\x86_64\
        shell: cmd

      - name: Upload math result
        uses: actions/upload-artifact@v1
        with:
          name: Assets
          path: Dev\Plugin\Assets\